export const cities = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "San Francisco",
    "Charlotte",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Kansas City",
    "Long Beach",
    "Mesa",
    "Atlanta",
    "Colorado Springs",
    "Virginia Beach",
    "Raleigh",
    "Omaha",
    "Miami",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Wichita",
    "New Orleans",
    "Srinagar",
    "Chennai",
    "Kolkata",
    "Bangalore",
    "Jammu",
    "Mumbai",
  ];
  
  export const countries = [
    "United States",
    "Canada",
    "United Kingdom",
    "Germany",
    "France",
    "Japan",
    "Australia",
    "Italy",
    "Brazil",
    "China",
    "South Korea",
    "Spain",
    "Mexico",
    "Indonesia",
    "Netherlands",
    "Turkey",
    "Saudi Arabia",
    "Switzerland",
    "Sweden",
    "Norway",
    "Denmark",
    "Poland",
    "Finland",
    "Belgium",
    "India",
    "Russia",
    "South Africa",
    "Argentina",
    "Austria",
    "Portugal",
    "Greece",
    "Israel",
    "Ireland",
    "Singapore",
    "Malaysia",
    "Philippines",
    "New Zealand",
    "Egypt",
    "Thailand",
    "Ukraine",
    "Vietnam",
    "Hungary",
    "Czech Republic",
    "Chile",
    "Romania",
    "Pakistan",
    "Bangladesh",
    "Kenya",
    "Nigeria",
    "Morocco"
  ];
  